apiVersion: v1
kind: Service
metadata:
  name: t8d-webapp
spec:
  type: NodePort
  selector:
    app: t8d-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  