apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: t8d-webapp
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: t8d-webapp
  template:
    metadata:
      labels:
        app: t8d-webapp
    spec:
      containers:
      - name: t8d-webapp
        image: t8d-miniserver/t8d-webapp-image:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 5
  
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
