---
- name: Check if node is already joined to cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Read join command from local file
  local_action:
    module: slurp
    src: "./k8s-join-command.sh"
  register: join_command_b64
  when: not kubelet_conf.stat.exists

- name: Decode join command
  set_fact:
    join_command: "{{ join_command_b64.content | b64decode | trim }}"
  when: not kubelet_conf.stat.exists and join_command_b64 is defined

- name: Join worker node to cluster
  command: "{{ join_command }}"
  when: not kubelet_conf.stat.exists and join_command is defined

- name: Label worker nodes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        labels: "{{ k8s_node_labels }}"
    merge_type: strategic-merge
    kubeconfig: /etc/kubernetes/admin.conf
  delegate_to: "{{ groups['k8s_masters'][0] }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: k8s_node_labels is defined
