---
- name: Check if Kubernetes is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Initialize Kubernetes cluster
  command: >
    kubeadm init
    --pod-network-cidr={{ k8s_pod_network_cidr }}
    --service-cidr={{ k8s_service_subnet }}
    --apiserver-advertise-address={{ k8s_api_server_advertise_address }}
    --apiserver-bind-port={{ k8s_api_server_bind_port }}
    --control-plane-endpoint={{ k8s_control_plane_endpoint }}
    --upload-certs
  when: not k8s_admin_conf.stat.exists
  register: kubeadm_init

- name: Create .kube directory for root
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to root's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0600'

- name: Create .kube directory for ansible user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Copy admin.conf to ansible user's kubeconfig
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Get join command for worker nodes
  command: kubeadm token create --print-join-command
  register: k8s_join_command
  when: kubeadm_init is changed

- name: Save join command to local file
  local_action:
    module: copy
    content: "{{ k8s_join_command.stdout }}"
    dest: "./k8s-join-command.sh"
    mode: '0755'
  when: k8s_join_command is defined and k8s_join_command.stdout is defined
