---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required system packages
  apt:
    name: "{{ system_packages }}"
    state: present

- name: Disable swap permanently
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  notify: disable swap

- name: Disable swap immediately
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Load required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure kernel modules load on boot
  lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: yes
  loop:
    - overlay
    - br_netfilter

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }

- name: Set timezone
  timezone:
    name: "{{ timezone }}"

- name: Configure NTP
  apt:
    name: ntp
    state: present

- name: Configure NTP servers
  lineinfile:
    path: /etc/ntp.conf
    regexp: '^server '
    line: "server {{ item }}"
  loop: "{{ ntp_servers }}"
  notify: restart ntp

# Handlers are defined in the main playbook, not in task files
